#!/bin/sh

# Stop if any commands throw errors
set -e

if [ "$#" -lt "1" ]; then
    echo "USAGE: enhance_coolness BRANCH_NAME SLEEP_SECONDS"
    exit 1
fi

COOLNESS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BRANCH_NAME=$1
SLEEP_SECONDS=${2:-1}

while [ 1 ]; do
    # Check if there are new commits
    echo -n ▶▶▶ Checking for new commits...
    git fetch
    BEHIND=`git status -bs | grep -o "behind"` || echo "nope"
    # If so, merge, process, and commit
    if [ "$BEHIND" = "behind" ]; then
        echo yup!
        echo ▶▶▶ Making project cooler...
        git merge --ff-only origin/$BRANCH_NAME && \
            $COOLNESS_DIR/process-changed-files && \
            git commit -m "Make project cooler" && \
            git push origin $BRANCH_NAME
    fi
    echo ▶▶▶ Sleeping for $SLEEP_SECONDS seconds
    sleep $SLEEP_SECONDS
done
