#!/bin/sh

# Stop if any commands throw errors
set -e

SLEEP_SECONDS=${1:-5}
if ! [[ "$SLEEP_SECONDS" =~ ^[0-9]+$ ]]; then
    echo "USAGE: enhance_coolness [SLEEP_SECONDS]"
    exit 1
fi

BRANCH_NAME=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_NAME##refs/heads/}
if [ -z "$BRANCH_NAME" ]; then
    echo "Could not determine the current branch"
    exit 2
fi

COOLNESS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while [ 1 ]; do
    echo -n ▶▶▶ Checking for new commits...
    git fetch
    BEHIND=`git status -bs | grep -o "behind"` || echo "nope"
    if [ "$BEHIND" = "behind" ]; then
        echo yup!
        echo ▶▶▶ Making project cooler...
        git merge --ff-only origin/$BRANCH_NAME && \
            $COOLNESS_DIR/process-changed-files && \
            git commit -m "Make project cooler" && \
            git push origin $BRANCH_NAME
    fi
    if [ "$SLEEP_SECONDS" -ge "1" ]; then
        echo ▶▶▶ Sleeping for $SLEEP_SECONDS seconds
        sleep $SLEEP_SECONDS
    fi
done
