#!/bin/sh

if (( $# != 2 )); then
    echo "USAGE: mibbot REPOSITORY_PATH BRANCH_NAME"
    exit 1
fi

# Stop if any commands throw errors
set -e

cd "$1" || exit 2
while [ 1 ] do
    # Check if there are new commits
    git fetch
    BEHIND=`git status -bs | grep -o "behind"`
    # If so, merge, process, and commit
    if [ $BEHIND = "behind" ]; then
        git merge --ff-only && \
            ./process-changed-files && \
            git commit -m "Make project cooler" && \
            git push origin $2
    fi
    sleep 5
done
